version: "3.8"
services:
  coolrabbit:
    image: rabbitmq:3-management-alpine
    container_name: 'coolrabbit'
    ports:
      - "5671:5672"
      - "15671:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  awesomerabbit:
    image: rabbitmq:3-management-alpine
    container_name: 'awesomerabbit'
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3